### ISSUE TITLE
How would you implement GetMany with gate?

### ISSUE THREAD

**Issue by jub0bs** [neild/gate#1]
In his GopherCon 2018 talk, Bryan C. Mills illustrates the shortcomings (spurious wakeups, specifically) of `sync.Cond` through [a `GetMany(n int) []Item` method on his queue type](https://www.youtube.com/watch?v=5zXAHh5tJqQ&t=764s).

If you were to add the following method to your queue (still based on your gate abstraction), 

```go
func (q *Queue[T]) GetMany(ctx context.Context, n int) ([]T, error)
```

how would you implement it? This still isn't clear to me.

**Comment by neild** [comment]
GetMany requires something more complicated, because you need more than one bit of state. I wouldn't use a gate for a queue which needs to support a GetMany that blocks until the full request size can be satisfied. (I don't think I've ever encountered a case where that's a useful operation, however, as opposed to "get up to N elements, return less if that's all that's available".)

That said, you could do something like this:

- the queue includes an internal queue of waiters
- the queue's gate condition is set if the queue contains enough elements to satisfy the head of the waiter queue
- GetMany is:
   1. lock the gate
   1. if the waiter queue is empty and the request can be satisfied:
      - take the items
      - unlock the gate
      - return
   1. add the current request to the waiter queue
   1. unlock the gate
   1. wait on the gate
      - if successful: take the items
      - if unsuccessful: lock the gate
   1. remove the request from the waiter queue
   1. return

**Comment by jub0bs** [comment]
Thanks for the thorough explanation! I have no remaining questions.
